version: "3.8"

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/sausage-store-backend:latest
    container_name: sausage-store-backend
    build:
      dockerfile: backend/Dockerfile
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    restart: always
    networks:
      - sausage_network

  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-store-frontend:latest
    volumes:
      - /tmp/${CI_PROJECT_DIR}/frontend/default.conf:/etc/nginx/conf.d/default.conf
    container_name: sausage-store-frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - sausage_network

networks:
  sausage_network: