version: "3.8"

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:latest
    container_name: sausage-backend
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    networks:
      - sausage-network

  backend-report:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend-report:latest
    container_name: sausage-backend-report
    restart: always
    environment:
      PORT: 8081
      DB: ${REPORTS_MONGODB_URI}
    networks:
      - sausage-network

  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-frontend:latest
    volumes:
      - /tmp/${CI_PROJECT_DIR}/frontend/default.conf:/etc/nginx/conf.d/default.conf
    container_name: sausage-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - sausage-network

networks:
  sausage-network:
    driver: bridge

