include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  
stages:
  - build
  - test
  - notify
build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/**/*
  cache:
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  script:
    - cd backend
    - mvn -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -Dversion.application="0.0.1" package
    - echo "PREV_JOB_ID=${CI_JOB_ID}" > build.env
    - echo "MAVEN_REPO_PATH=${CI_PROJECT_DIR}/.m2/repository" >> build.env
  artifacts:
    reports:
      dotenv: backend/build.env
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
      - .m2/
    expire_in: 1 day

spotbugs-sast:
  stage: test
  rules:
    - changes:
        - backend/*  
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
#    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  needs:
    - build-backend-code-job


 

sonarqube-backend-sast:
  stage: test
  only:
    changes:
    - backend/*  
  variables:
#    MAVEN_REPO_PATH: $CI_PROJECT_DIR/.m2/repository
    SONAR_PROJECT_NAME: "24_ГЛЕБФЕДОТОВ_БЭКЭНД"
  image: maven:3.8-openjdk-16
  script:
    - cd backend
    - >
        mvn 
        --batch-mode verify sonar:sonar 
        -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository 
        -Dsonar.projectName=$SONAR_PROJECT_NAME 
        -Dsonar.host.url=$SONARQUBE_URL 
        -Dsonar.login=$SONAR_LOGIN_BACKEND 
        -Dsonar.projectKey=$SONAR_PROJECT_KEY_BACK 
        -Dsonar.qualitygate.wait=true
  needs:
    - build-backend-code-job
    



telegram-notification-backend:
  variables:
      TEXT: "Глеб Федотов собрал backend ${CI_PROJECT_URL}/-/jobs/${PREV_JOB_ID}/artifacts/download"
      TLGRM: "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"
  stage: notify
  only:
    changes:
    - backend/*
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - ls backend/target/*
    - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002134018008\", \"text\": \"${TEXT}\"}" ${TLGRM}'
  needs:
    - build-backend-code-job


