apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-024-07/sausage-store/sausage-backend:latest
          name: backend
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://rc1d-6ltxi07qdaaunpa5.mdb.yandexcloud.net:6432/std-024-07?ssl=true
          ports:
            - name: backend
              containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            # проверка живучести выполнит запрос HTTP GET       
            httpGet:
              # путь к запросу в HTTP-запросе          
              path: /actuator/health
              # порт, к которому должна подключиться проверка        
              port: 8080
            # перед исполнением первой проверки подождать 15 секунд, пока стартанёт бэкенд          
            initialDelaySeconds: 15
            # период выполнения проверки
            periodSeconds: 30
            # максимальное время выполнения проверки (по умолчанию 1 раз)
            timeoutSeconds: 2
            # сколько раз пробовать попытку, если она провалилась (по умолчанию 1 раз)
            failureThreshold: 6
      # чтобы Кубер мог скачивать образы из нашего GitLab Registry  
      imagePullSecrets:
        - name: docker-config-secret
