# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDI0LTA3IiwicGFzc3dvcmQiOiJrZVZWX3NmTXp5cDh1Zi1TSFdoTCIsImF1dGgiOiJjM1JrTFRBeU5DMHdOenByWlZaV1gzTm1UWHA1Y0RoMVppMVRTRmRvVEE9PSJ9fX0=
kind: Secret
metadata:
  name: docker-config-secret
  namespace: std-024-07
type: kubernetes.io/dockerconfigjson

