apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  revisionHistoryLimit: 12
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - backend-report
            topologyKey: "kubernetes.io/hostname"
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-024-07/sausage-store/sausage-backend-report:latest
          name: backend-report
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: VERSION
              value: latest
            - name: PORT
              value: "8080"
            - name: REPORT_PATH
              value: /var/www-data/htdocs
            - name: DB
              value: $(REPORTS_MONGODB_URI)                 
          ports:
            - name: backend-report
              containerPort: 8080 
      imagePullSecrets:
        - name: docker-config-secret
